import "server-only";
import ExcelJS, { type Cell, type Fill, type Font, type Worksheet } from "exceljs";
import { parseMarkdown, type DocumentBlock } from "./content";

const PURPLE = "8B2CE0";
const VIOLET = "7030B5";
const PINK = "E8447A";
const INK = "1A1A1A";
const SLATE = "5B5B63";
const PAPER = "FFFDFB";
const BLUSH = "F7DFEA";
const LILAC = "EADCF5";
const BLUE = "D8EEF8";
const LINE = "EADBD5";

type WorkbookModule = { type: string; title: string; markdown: string };
type SpreadsheetArgs = {
  companyName: string;
  title: string;
  markdown: string;
  updatedAt: Date;
  sourceCount: number;
  modules?: WorkbookModule[];
};

const titleFill: Fill = { type: "pattern", pattern: "solid", fgColor: { argb: PURPLE } };
const titleFont: Partial<Font> = { name: "Arial", color: { argb: "FFFFFF" }, bold: true };

function sheetSafe(value: string): string {
  return value.replace(/[\\/*?:\[\]]/g, " ").replace(/\s+/g, " ").trim().slice(0, 31) || "Sheet";
}

function uniqueSheetName(workbook: ExcelJS.Workbook, requested: string): string {
  const base = sheetSafe(requested);
  if (!workbook.getWorksheet(base)) return base;
  for (let index = 2; index < 100; index += 1) {
    const suffix = ` ${index}`;
    const candidate = `${base.slice(0, 31 - suffix.length)}${suffix}`;
    if (!workbook.getWorksheet(candidate)) return candidate;
  }
  return `${base.slice(0, 26)} ${Date.now().toString().slice(-4)}`;
}

function tableSafe(value: string): string {
  const safe = value.replace(/[^a-z0-9_]/gi, "_").replace(/^[^a-z_]+/i, "T_").slice(0, 220);
  return safe || `Table_${Date.now()}`;
}

function setBaseSheet(sheet: Worksheet) {
  sheet.properties.defaultRowHeight = 19;
  sheet.views = [{ state: "frozen", ySplit: 4, showGridLines: false }];
  sheet.pageSetup = { orientation: "landscape", fitToPage: true, fitToWidth: 1, fitToHeight: 0, margins: { left: 0.25, right: 0.25, top: 0.45, bottom: 0.45, header: 0.2, footer: 0.2 } };
  sheet.headerFooter.oddHeader = `&L&8THE SMARKETERS / SMARK CONNECT&R&8${sheet.name}`;
  sheet.headerFooter.oddFooter = "&L&8Evidence-led AI CMO workbook&R&8Page &P of &N";
}

function applyCellBase(cell: Cell) {
  cell.font = { name: "Arial", size: 10, color: { argb: SLATE } };
  cell.alignment = { vertical: "top", wrapText: true };
  cell.border = { bottom: { style: "hair", color: { argb: LINE } } };
}

function setColumnWidths(sheet: Worksheet, widths: number[]) {
  widths.forEach((width, index) => { sheet.getColumn(index + 1).width = Math.min(52, Math.max(12, width)); });
}

function styleDataTable(sheet: Worksheet, headerRow: number, columnCount: number, dataRowCount: number) {
  for (let column = 1; column <= columnCount; column += 1) {
    const header = sheet.getCell(headerRow, column);
    header.fill = titleFill;
    header.font = { ...titleFont, size: 9 };
    header.alignment = { vertical: "middle", wrapText: true };
  }
  sheet.getRow(headerRow).height = 24;
  for (let index = 0; index < dataRowCount; index += 1) {
    const row = sheet.getRow(headerRow + index + 1);
    row.eachCell({ includeEmpty: true }, (cell, column) => {
      if (column > columnCount) return;
      applyCellBase(cell);
      cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: index % 2 ? PAPER : BLUE } };
    });
  }
}

function addSheetHeader(sheet: Worksheet, args: { title: string; subtitle: string; companyName: string }) {
  sheet.mergeCells("A1:H1");
  const title = sheet.getCell("A1");
  title.value = args.title;
  title.font = { name: "Arial", size: 18, bold: true, color: { argb: INK } };
  title.alignment = { vertical: "middle" };
  sheet.getRow(1).height = 28;
  sheet.mergeCells("A2:H2");
  const subtitle = sheet.getCell("A2");
  subtitle.value = args.subtitle;
  subtitle.font = { name: "Arial", size: 9, italic: true, color: { argb: SLATE } };
  subtitle.fill = { type: "pattern", pattern: "solid", fgColor: { argb: BLUSH } };
  subtitle.alignment = { vertical: "middle", wrapText: true };
  sheet.getRow(2).height = 25;
  sheet.mergeCells("A3:H3");
  const meta = sheet.getCell("A3");
  meta.value = `${args.companyName}  |  Generated by Smark Connect`;
  meta.font = { name: "Arial", size: 8, bold: true, color: { argb: VIOLET } };
  meta.alignment = { vertical: "middle" };
}

function firstNarrative(blocks: DocumentBlock[]): string {
  const block = blocks.find((item) => item.type === "paragraph" || item.type === "quote" || item.type === "bullet");
  return block && "text" in block ? block.text.slice(0, 420) : "See the structured module sheet for the evidence, decisions, and actions.";
}

function sourceUrls(markdown: string): string[] {
  return Array.from(markdown.matchAll(/https?:\/\/[^\s)\]>]+/g), (match) => match[0].replace(/[.,;:]$/, ""))
    .filter((url, index, values) => values.indexOf(url) === index);
}

function addOverview(workbook: ExcelJS.Workbook, args: SpreadsheetArgs, modules: WorkbookModule[]) {
  const sheet = workbook.addWorksheet("Overview", { properties: { tabColor: { argb: PURPLE } } });
  setBaseSheet(sheet);
  addSheetHeader(sheet, { title: args.title, subtitle: "Decision-ready workbook: narrative modules, structured tables, and a source register.", companyName: args.companyName });
  setColumnWidths(sheet, [22, 28, 62, 16, 16, 16, 16, 16]);

  const facts = [
    ["UPDATED", args.updatedAt],
    ["MODULES", modules.length],
    ["SOURCES", args.sourceCount],
    ["FORMAT", "XLSX · editable and filterable"],
  ] as Array<[string, string | number | Date]>;
  facts.forEach(([label, value], index) => {
    const column = 1 + index * 2;
    const labelCell = sheet.getCell(5, column);
    const valueCell = sheet.getCell(6, column);
    sheet.mergeCells(5, column, 5, column + 1);
    sheet.mergeCells(6, column, 6, column + 1);
    labelCell.value = label;
    labelCell.fill = titleFill;
    labelCell.font = { ...titleFont, size: 8 };
    labelCell.alignment = { vertical: "middle", horizontal: "center" };
    valueCell.value = value;
    valueCell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: index % 2 ? LILAC : BLUE } };
    valueCell.font = { name: "Arial", size: 12, bold: true, color: { argb: INK } };
    valueCell.alignment = { vertical: "middle", horizontal: "center", wrapText: true };
    if (value instanceof Date) valueCell.numFmt = "mmm d, yyyy";
    sheet.getRow(6).height = 34;
  });

  const rows = modules.map((module, index) => {
    const blocks = parseMarkdown(module.markdown);
    return [index + 1, module.title, firstNarrative(blocks), blocks.filter((block) => block.type === "table").length, sourceUrls(module.markdown).length];
  });
  sheet.addTable({
    name: "Workbook_Module_Map",
    ref: "A9",
    headerRow: true,
    totalsRow: false,
    style: { theme: "TableStyleMedium4", showRowStripes: true },
    columns: ["#", "Module", "Executive takeaway", "Structured tables", "Source links"].map((name) => ({ name })),
    rows,
  });
  styleDataTable(sheet, 9, 5, rows.length);
  sheet.getColumn(1).width = 7;
  sheet.getColumn(2).width = 28;
  sheet.getColumn(3).width = 72;
  sheet.getColumn(4).width = 18;
  sheet.getColumn(5).width = 15;
  sheet.getRows(10, Math.max(1, rows.length))?.forEach((row) => { row.height = 44; row.eachCell(applyCellBase); });
}

function addNarrativeSheet(workbook: ExcelJS.Workbook, args: SpreadsheetArgs, module: WorkbookModule, moduleIndex: number) {
  const blocks = parseMarkdown(module.markdown);
  const sheet = workbook.addWorksheet(uniqueSheetName(workbook, module.title), { properties: { tabColor: { argb: moduleIndex % 2 ? PINK : VIOLET } } });
  setBaseSheet(sheet);
  addSheetHeader(sheet, { title: module.title, subtitle: "Evidence → interpretation → decision → confidence → validation → measurement", companyName: args.companyName });
  setColumnWidths(sheet, [7, 30, 72, 24, 18, 18, 18, 18]);
  let row = 5;
  let section = "Executive synthesis";
  let tableIndex = 0;

  for (const block of blocks) {
    if (block.type === "h1") continue;
    if (block.type === "h2" || block.type === "h3") {
      section = block.text;
      sheet.mergeCells(row, 1, row, 8);
      const cell = sheet.getCell(row, 1);
      cell.value = block.text;
      cell.fill = block.type === "h2" ? titleFill : { type: "pattern", pattern: "solid", fgColor: { argb: LILAC } };
      cell.font = { name: "Arial", bold: true, size: block.type === "h2" ? 11 : 10, color: { argb: block.type === "h2" ? "FFFFFF" : VIOLET } };
      cell.alignment = { vertical: "middle", wrapText: true };
      sheet.getRow(row).height = 24;
      row += 1;
      continue;
    }
    if (block.type === "table") {
      tableIndex += 1;
      const tableSheet = workbook.addWorksheet(uniqueSheetName(workbook, `${module.title.slice(0, 16)} · ${section.slice(0, 12)}`), { properties: { tabColor: { argb: BLUE } } });
      setBaseSheet(tableSheet);
      addSheetHeader(tableSheet, { title: section, subtitle: `${module.title} · structured, filterable export`, companyName: args.companyName });
      const headers = block.rows[0].map((value, index) => value || `Column ${index + 1}`);
      const dataRows = block.rows.slice(1).map((values) => headers.map((_, index) => values[index] ?? ""));
      tableSheet.addTable({ name: tableSafe(`Module_${moduleIndex + 1}_Table_${tableIndex}`), ref: "A5", headerRow: true, totalsRow: false, style: { theme: "TableStyleLight1", showRowStripes: false }, columns: headers.map((name) => ({ name })), rows: dataRows });
      styleDataTable(tableSheet, 5, headers.length, dataRows.length);
      headers.forEach((_, index) => {
        const longest = Math.max(headers[index].length, ...dataRows.slice(0, 60).map((values) => String(values[index] ?? "").length));
        tableSheet.getColumn(index + 1).width = Math.min(52, Math.max(13, Math.ceil(longest * 0.78)));
      });
      tableSheet.getRows(6, Math.max(1, dataRows.length))?.forEach((tableRow) => { tableRow.height = 34; tableRow.eachCell(applyCellBase); });
      sheet.mergeCells(row, 1, row, 8);
      const reference = sheet.getCell(row, 1);
      reference.value = { text: `Open structured table: ${tableSheet.name}`, hyperlink: `#'${tableSheet.name.replace(/'/g, "''")}'!A1` };
      reference.font = { name: "Arial", size: 9, bold: true, color: { argb: PURPLE }, underline: true };
      reference.fill = { type: "pattern", pattern: "solid", fgColor: { argb: BLUE } };
      reference.alignment = { vertical: "middle" };
      row += 2;
      continue;
    }
    const marker = block.type === "bullet" ? "BULLET" : block.type === "number" ? "STEP" : block.type === "quote" ? "NOTE" : "";
    if (marker) {
      sheet.getCell(row, 1).value = marker;
      sheet.getCell(row, 1).font = { name: "Arial", size: 8, bold: true, color: { argb: PURPLE } };
      sheet.getCell(row, 1).alignment = { vertical: "top", horizontal: "center", wrapText: true };
    }
    sheet.mergeCells(row, 2, row, 8);
    const cell = sheet.getCell(row, 2);
    cell.value = block.text;
    cell.font = { name: "Arial", size: 10, color: { argb: block.type === "quote" ? INK : SLATE }, italic: block.type === "quote" };
    cell.alignment = { vertical: "top", wrapText: true };
    if (block.type === "quote") cell.fill = { type: "pattern", pattern: "solid", fgColor: { argb: BLUSH } };
    sheet.getRow(row).height = Math.min(92, Math.max(23, 18 + Math.ceil(block.text.length / 115) * 15));
    row += 1;
  }
  sheet.autoFilter = { from: "A4", to: "H4" };
}

function addSources(workbook: ExcelJS.Workbook, args: SpreadsheetArgs, modules: WorkbookModule[]) {
  const sheet = workbook.addWorksheet(uniqueSheetName(workbook, "Source Register"), { properties: { tabColor: { argb: PINK } } });
  setBaseSheet(sheet);
  addSheetHeader(sheet, { title: "Source Register", subtitle: "URLs preserved from the generated document evidence. Verify freshness before execution.", companyName: args.companyName });
  setColumnWidths(sheet, [8, 28, 72, 18, 18, 18, 18, 18]);
  const rows = modules.flatMap((module) => sourceUrls(module.markdown).map((url) => [module.title, url, "Generated evidence pack"]));
  const uniqueRows = rows.filter((row, index, values) => values.findIndex((candidate) => candidate[1] === row[1]) === index);
  sheet.addTable({ name: "Workbook_Source_Register", ref: "A5", headerRow: true, totalsRow: false, style: { theme: "TableStyleMedium4", showRowStripes: true }, columns: ["Module", "Source URL", "Use"].map((name) => ({ name })), rows: uniqueRows.length ? uniqueRows : [["Workbook", "No source URL embedded", "Connect or regenerate with source evidence"]] });
  styleDataTable(sheet, 5, 3, Math.max(1, uniqueRows.length));
  sheet.getColumn(1).width = 28;
  sheet.getColumn(2).width = 82;
  sheet.getColumn(3).width = 34;
  sheet.getRows(6, Math.max(1, uniqueRows.length))?.forEach((row) => { row.height = 30; row.eachCell(applyCellBase); });
}

export async function createBrandedXlsx(args: SpreadsheetArgs): Promise<Buffer> {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = "Smark Connect";
  workbook.company = "The Smarketers";
  workbook.title = `${args.companyName} - ${args.title}`;
  workbook.subject = "Evidence-led AI CMO workbook";
  workbook.description = "A structured, editable spreadsheet export generated by Smark Connect.";
  workbook.created = args.updatedAt;
  workbook.modified = args.updatedAt;
  workbook.calcProperties.fullCalcOnLoad = true;

  const modules = args.modules?.length ? args.modules : [{ type: "DOCUMENT", title: args.title, markdown: args.markdown }];
  addOverview(workbook, args, modules);
  modules.forEach((module, index) => addNarrativeSheet(workbook, args, module, index));
  addSources(workbook, args, modules);

  workbook.eachSheet((sheet) => {
    sheet.eachRow((row) => row.eachCell((cell) => {
      if (!cell.font) cell.font = { name: "Arial", size: 10, color: { argb: SLATE } };
    }));
    sheet.getCell("A1").note = "Generated from Smark Connect document evidence. Source URLs and confidence boundaries should be reviewed before execution.";
  });
  const output = await workbook.xlsx.writeBuffer();
  return Buffer.from(output);
}
